### ISSUE TITLE
1 or 2 digits behind the decimal point

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1292]
See http://rsr.akvo.org/projects/?title=&location=&status=&organisation=&sector=
Issue: one digit shown where one would expect 2 (.80):

![screenshot 2015-03-03 15 49 57](https://cloud.githubusercontent.com/assets/8478175/6464808/232c9a4c-c1bd-11e4-8da1-8c6986a7ee71.png)

Same on financial info page:
![screenshot 2015-03-03 15 48 37](https://cloud.githubusercontent.com/assets/8478175/6464816/2bf0a9e8-c1bd-11e4-94c3-6884d4e25ac6.png)

**Comment by adriancollier** [comment]
Agreed, we should standardise and always show the decimal points.

At the same time we should align the numbers to the right so that it becomes easier to evaluate the different values displayed.

**Comment by gabemart** [comment]
In addition to the financial info page, should we also align-right the budget on the project listing page?

Current:

![budget-alignleft](https://cloud.githubusercontent.com/assets/2589977/6597121/26ff7ef6-c7f2-11e4-81ce-b5a6a5c95c86.png)

With align-right:

![budget-alignright](https://cloud.githubusercontent.com/assets/2589977/6597123/2df5df7a-c7f2-11e4-8c25-3c8119bbfe74.png)

I vote yes

**Comment by gabemart** [comment]
@KasperBrandt did we decide against adding decimals on the project listing page too, or should I do that now?

**Comment by KasperBrandt** [comment]
@gabemart We haven't really decided on that. I tried it this morning and then realised that there's a limited space for numbers there.. But I think we should, in order to prevent the ".8" cases (see first image in this issue). So yeah, go ahead (same goes for the right alignment).

**Comment by adriancollier** [comment]
I think the safest option for consistency is to always display them.

**Comment by gabemart** [comment]
There remains the question of how to align on narrower viewports - right alignment puts the currency amount very far from their labels. In my opinion makes things harder rather than easier to compare. Shall I only adjust the alignment on larger viewports for now?

![narrowviewport](https://cloud.githubusercontent.com/assets/2589977/6597563/865e5572-c7f5-11e4-939e-86720d60375f.png)

Another approach would be to narrow the width of the entire column of content, like so: 

![financecolumn](https://cloud.githubusercontent.com/assets/2589977/6597731/66d22f2a-c7f6-11e4-9af8-dc08ccfb034a.png)

**Comment by KasperBrandt** [comment]
@gabemart I think the second option looks good. I think we should fix it so that the amounts are shown on the same line as the labels as well.

**Comment by gabemart** [comment]
@KasperBrandt @loicsans is the use of a space between the currency symbol and the currency amount in some places but not others by design?

When using align-right, sometimes line wrapping messes up the display

![foo](https://cloud.githubusercontent.com/assets/2589977/6598143/7ffbe402-c7f9-11e4-8594-23fa199f69e1.png)

There are different ways to approach this, but the easiest is just to never display a space between the currency symbol and the currency amount. Shall I take out the spaces?

**Comment by KasperBrandt** [comment]
@gabemart Oh, I just put that in today because I thought it looked nicer. Maybe it's easier to remove the space again and keep it as is.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the project finance page
WHEN an amount is shown
THEN it is aligned to the right
AND there's two digits behind the comma

GIVEN the projects listing page
WHEN the budget is shown
THEN it is aligned to the right
AND there's two digits behind the comma
