### ISSUE TITLE
Publishing of Projects in RSR

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1310]
Following on from the Version 3 changes, we implemented the ability for Organisation Admins to publish their projects.

To help to emphasise the data quality in RSR, we need to add validation and modify the permissions on the publication process.

- [ ] Projects in the Admin can only be saved when all mandatory fields have been entered
- [ ] Projects have an additional layer of publication requirements e.g. Image and Location
- [ ] Admin users can Publish or Unpublish projects that meet both mandatory and publication fields are completed from within MyRSR
- [ ] Admin users cannot enter the Publication Status section of the Admin
- [ ] Akvo Admin users (Support users) can access the Publication Status section of the Admin
- [ ] Akvo Admin users (Support users) can Publish a project without adhering to the publication requirements

**Comment by JosjeS** [comment]
I think it makes sense to let partners publish their projects, just two comments:

1. "Projects in the Admin can only be saved when all mandatory fields have been entered" I think we should allow partners to save projects before entering all the information because sometimes you cannot fill in a field yet. And I think what we want to avoid is organisations then temporarily fill in place holder information or just a hyphen to be able to save it and later maybe forget to replace it.
Though publishing when mandatory fields are not filled in should not be allowed.  

2. I am wondering if we should let organisations 'unpublish' their projects. Because when then something happens during the project the organisation doesn't like or when it doesn't go the way as planned they might be quick to unpublish a project while I think we might want to stimulate adding an update noting why things did not go as planned and leaving the project online.

**Comment by KasperBrandt** [comment]
Will be fixed by replacing the admin.
