### ISSUE TITLE
Improve search and filter

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1400]
The search and filtering on the project list is confusing for our users. Some issues:
- [ ] Selecting a filter will filter immediately, thus not allowing the users to select multiple filters at once
- [ ] It is possible to filter through the search box. Applying a filter there first and then search will remain the filter.
- [ ] After selecting a filter in the search box, it is possible to click the 'Update list' button. Instead of filtering, it will then perform a search.

**Comment by adriancollier** [comment]
Thoughts about whether changes can be made within this page to apply the filter to only the results without loading the whole page again.

This should be possible and could resolve a lot of the issues we are hearing about.

**Comment by lauraroverts** [comment]
Feedback from YEP training 8 October 2015: 
RSR search button (rsr.akvo.org) does not work properly. For a user it is not clear if it searches on title, organstion name or anything else. If I type 'Akvo' and press search, I get 4 hits. If I type Akvo, select Akvo from the dropdown and wait (without clicking search), I get 122 hits. This is confusing for users (especially when it takes a long time to load).

Also the 'advanced fitlers' button does not stand out. Users overlook the button. 

On a small laptop screen, the popup window for Advanced filters is not very obvious. In the YEP training someone saw what you see in the screenshot below. As a result chose a country from the first location dropdown and clicked the blue search button (because you don't see the 'apply filter' button without scrolling down. Then you don't filter, but search. 
![screen shot 2015-10-09 at 14 59 24](https://cloud.githubusercontent.com/assets/4179989/10394282/693e5bca-6e96-11e5-8727-245a6c704ba0.png)

**Comment by lauraroverts** [comment]
Another case: 
I just added http://rsr.akvo.org/en/organisation/3150/ to project http://rsr.akvo.org/en/project/3212/. 
If I search for 'World Vision Nederland' in the searchbox at http://rsr.akvo.org/en/project/3212/, I get 0 projects. If I use the advanced filters and filter for 'World Vision Nederland', I do get project 3150. 

This is confusing. I expect to find the project too if I search for the organisation by using the searchbox.

**Comment by punchagan** [comment]
Seems related to #2552 and #2598

**Comment by punchagan** [comment]
Super stale, and most issues are fixed. Closing.
