### ISSUE TITLE
Filtering Projects by title behaviour is odd

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-rsr#1465]
## Test plan
1. In the project editor, add a leading or trailing space to the project title or subtitle
2. Save section
3. Reload page or visit project page
4. There should not be any leading or trailing spaces

## Issue description
I'm not sure if it's related to #1338 or not, but the sort by title on project listings doesn't seem to be working as expected. See here:

http://rsr.uat.akvo.org/projects/?page=1&sort_by=-title

**Comment by zzgvh** [comment]
The problem lies in the data. Try http://rsr.uat.akvo.org/projects/?page=1&sort_by=title to get sorted A-Z. The fist projects (as of this writing) are 2531, 317 and 2118 all of which have a leading space in their titles! After that we have a project with a leading **'** and then follow a number of projects with an integer as the first char of the title.

So it works as intended :stuck_out_tongue: 

On a more serious note, we can create fix the three (or so, dunno if there's more on live) projects with leading spaces and then add form validation forbidding leading spaces. After that it becomes somewhat tricky. You can sort using regexp_replace() ([see here](http://stackoverflow.com/questions/12965463/humanized-or-natural-number-sorting-of-mixed-word-and-number-strings)) but it's not trivial to write a good regex and I have no idea of the performance impact of it. I think it's possible to create an index using similar technique but that feels like an even deeper rabbit hole.

**Comment by KasperBrandt** [comment]
I would suggest a quick fix: strip all leading spaces of existing projects and add a validation on the project model.
