### ISSUE TITLE
Indicating what is hidden

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1512]
Copied from feedback document Thomas 02-4-2015: 
We are not consistent in showing a user what is hidden or not. We hide the map and we have a “Show Map +” indication. But we hide Background, Current situation, Project plan, Sustainability, Goals overview without any indication that this sections can be expanded. 

Suggestion is to create an indication that you can expand on things.

**Comment by KasperBrandt** [comment]
I guess this is a duplicate from a different issue, since this has already been fixed. A '+' or '-' sign has been added to the description fields on the project page. In addition, the foldable objects in the new project editor will also show a +/- sign to indicate that something can be hidden or not.
