### ISSUE TITLE
Akvo Pages information (materialized views)

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1515]
## Test plan
GIVEN core RSR and Akvo Pages
WHEN opening the filters on the project and organisation listing pages
THEN only countries that have results should be shown

GIVEN Akvo Pages only
WHEN opening the filters on the project, organisation and update listing pages
THEN only organisations that are relative to the page should appear in the filter list

## Issue description
At Akvo Pages the dropdowns to filter for an Organisation or Country include all organisations and countries that have got a project in RSR. E.g. http://washalliance.akvoapp.org/projects/. It would be great if at an Akvo Page only those organisations and countries that are linked to the partner's Akvo Page will appear in the dropdown. 

For the Dutch WASH Alliance that would mean only 8 countries show up in the dropdown, because they only work in 8 countries. 

It used to be like this in the old version of RSR.

**Comment by lauraroverts** [comment]
The comment above still applies for countries. 

However, for organsations the dropdown in Akvo Pages has disappeared, which doesn't make sense to me. If I look at http://washalliance.akvoapp.org/en/projects/ I want to be able to search for a partner that is linked to one of the WASH Alliance projects. Now the dropdown is gone, I need to know up front which organisations work in the alliance and type their name. I would like to see a dropdown. I can still start typing in the field so that I get suggestions of the organisation I'm looking for. 

At rsr.akvo.org I also would like to see a dropdown of all organisations in the RSR database. But here as well I would like to start typing, so that I get suggestions about which organisation I'm looking for, to avoid scrolling all the way down if I'm searching an organsation that starts with Z.

**Comment by KasperBrandt** [comment]
I propose to bring back the dropdowns for organisations on Akvo Pages, but to keep the search box on RSR itself. Because loading 2500+ organisations in one dropdown will not make it easy to search for an organisation, and it makes the page quite slow, whereas the current solution is quite elegant.

Agree?

**Comment by lauraroverts** [comment]
Akvo Pages should only have those organisations in the dropdown, that are linked to the projects in that specific Akvo Pages. Not all 2500+ organisations.

**Comment by zzgvh** [comment]
If I recall correctly the reason for removing the custom select with only partner organisations on Akvo Pages was that the performance of it was dismal, especially on sites relying on keywords, which I think is now the norm. The reason for that is that a complex query is required to calculate this list of organisations. On RSR it's much simpler since we list all organisations in the system.

One solution for Akvo Pages is to pre-compute the list of partners using materialized views. That way we could create a performant list of organiations for each instance of Pages.
