### ISSUE TITLE
Show clear 403 message

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1571]
## Test plan
GIVEN the My Projects page

WHEN a project is unpublished
THEN the 'Update' button should be disabled

WHEN the user is on the page
THEN the 'Add an update' button in the top navigation should not be displayed

WHEN a project's location doesn't have a country
THEN there should be a placeholder stating 'Location unknown'

WHEN a project doesn't have a title
THEN there should be a placeholder stating 'Untitled project'

## Issue description
When a user is logged in and goes to the "Add Update" page to update a non-published project, a simple 403 message (forbidden) is displayed.

To make it more clear that they can't post an update (or view the project) because the project is not published, we should provide a more user friendly forbidden message.

**Comment by zzgvh** [comment]
@gabemart I'm assigning this to you for a final UI touch. [These lines](https://github.com/akvo/akvo-rsr/blob/6da8cbe32f1c120bc56c23e8a792f0b3cba2aba4/akvo/templates/myrsr/my_projects.html#L86-L89) should be replaced with something like this:

```html
{% if project.is_published %}
  {% has_perm 'rsr.post_updates' project as can_add_update %}
  <a href="{% url 'add-update' project.pk %}">{% trans 'Update' %}</a>
{% else %}
  <!-- a greyed out button without a link -->
{% endif %}
```

This way we get a consistent look rather than the current cludge:

![screenshot_90](https://cloud.githubusercontent.com/assets/142613/9062995/d5866af2-3ac5-11e5-896d-f448c7163684.png)

Problem is I don't have a clue how to create such a disabled button...

**Comment by gabemart** [comment]
<img width="1249" alt="screen shot 2015-08-07 at 15 05 56" src="https://cloud.githubusercontent.com/assets/2589977/9137613/bbec9bcc-3d16-11e5-88f0-525a2ed0bc2e.png">

@zzgvh @KasperBrandt Here is my interpretation of a disabled button

**Comment by zzgvh** [comment]
Looks good to me! @KasperBrandt ?
