### ISSUE TITLE
Add organisations in project editor

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1746]
## Test plan
GIVEN the project editor
WHEN looking at section 3, partners
THEN there should be an 'Add new organisation' button

GIVEN the 'Add new organisation' button is clicked
WHEN the modal appears
THEN it should be possible to add a new organisation with a name, long name, IATI organisation ID, organisation type, and description

WHEN adding a new organisation
THEN the name and long name fields should be filled in
AND the name, long name and IATI organisation ID should not already exist in the database yet

WHEN an organisation has been added
THEN the modal should disappear
AND the new organisation should be selectable in the organisation typeaheads, except for the reporting organisation typeahead

## Issue description
It should be possible for organisation Admins to add a new organisation while they're in the project editor, so that they don't have to visit the old admin.

**Comment by gabemart** [comment]
@KasperBrandt For a modal dialog to add organisations, what set of fields would we need to support? The full set in the Django admin for adding organisations?

**Comment by lauraroverts** [comment]
Just looked at this via http://rsr.test.akvo.org/en/myrsr/project_editor/3591/
I clicked the 'add new organisation' button because I wanted to add Akvo as a new organisation. If I enter akvo in lower cases, I get a message 'organisation already exists'. However, if I enter AKVO in upper cases, I'm able to add the organisation. I would expect it gives me suggestions when I start typing the name of an organisation. 

The screenshot below shows 3 different Akvo's. It seems that name and long name need to be exactly the same, otherwise you can add the same organisation multiple times. I foresee a lot of duplications here. 

Furthermore wondering why we do not add certain fields anymore: location, contact details, website url etc. We could rethink what we want to show at an organisation page. Do we still want to show all information that has always been there? Or e.g. is the name of an organisation and the website url sufficient?

**Comment by gabemart** [comment]
>If I enter akvo in lower cases, I get a message 'organisation already exists'. However, if I enter AKVO in upper cases, I'm able to add the organisation. I would expect it gives me suggestions when I start typing the name of an organisation.

We can certainly make the check for existing organisations case-insensitive. We could go further, and strip out spaces before checking for equality, so that ` Akvo` will match `Akvo` and `Akvo    `. This is a very simple change to make.

**Comment by lauraroverts** [comment]
good idea
