### ISSUE TITLE
Results framework

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1773]
- [x] Markup for results framework on project page
- [x] Calculated results for parent / child relations
- [x] Import result (create parent result) in project editor

See;
- https://github.com/akvo/akvo-product-design/issues/6
- https://github.com/akvo/akvo-product-design/issues/101
- https://docs.google.com/document/d/1AVN8UqloWVM9vS57a1IUjed1BadchQs905zYFHztE6A/edit

And; [results framework iter 1.pdf](https://github.com/akvo/akvo-rsr/files/5769/results.framework.iter.1.pdf)

**Comment by zzgvh** [comment]
# Results framework notes

This is kind of a code review and discussion on the results framework. All code refereces are to the [issue/1773-results-framework branch's commit 3a492b04](https://github.com/akvo/akvo-rsr/tree/3a492b0454ce792994adc4e2316db2d594d9016c)

This is a complicated pile of code! And the subject made even more tricky to manage since the underlying spec, the IATI standard, is so "flimsy"! In light of that I think you've made a great job of getting all in place. I have a few areas of general discussion, where the code might be improved/refactored in a broader sense. However as I don't know all the ins and outs of how this is actually thought to work these are just suggestions and base for discussion.

One corollary of the code complexity though is that it needs more documentation. The interaction between the objects are really complex and I scratched my head quite a bit before I got the whole picture.

### Discussion on the data model
I'm wondering if one could use more foreign keys to simplify the lookup of Indicators and IndicatorPeriods by having foreign key or one-to-one fields for them similar to the Result.parent_result. It'd be a "tighter" link than the current and since I'm not 100% updated on the use cases for child results/indicators/periods this may be wrong. But the current solution seems brittle to me, if you can manipulate the child fields you run the risk of loosing the linkage.

Should IndicatorPeriod dates should be allowed to overlap? I can't see any restrictions in the IATI standard, but it seems very bad to allow overlap.

### Discussion on related projects

This is an interesing one. A project can declare a relation to another project, e.g. parent or child. But the declaration isn't strictly reciprocal, there's nothing in the IATI spec that says a child project has a parent. The code ([models/project.py#910](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/project.py#L910) and on) currently does  imply that, and I'm not sure that we should.

Given the above I would also suggest making this a field on the Project model using a "through=RelatedProject" attribute. This makes it clearer what we try to model here and should make the lookups simpler.

### Discussion on indicator values

It's really annoying that indicator values can be arbitrary strings! All those try:excepts and castings to Decimal are so annoying, and I wonder if it's possible to make a custom Model field that manages those issues. Ah, well. /rant

### IndicatorUpdate model

Do indicator updates have anything in common with regular updates? As it is now there's quite a few places where we branch depending on if it's regular or indicator updates that are to be handled. I think a cleaner solution is to create an IndicatorUpdate model and use that where appropriate.

A quick survey of the code hints at the photo being the only common field. This could well be duplicated. Alternatively a larger refactoring would be to create an UploadedImage model that's used everywhere we have pics. But that's a large general refactoring!

### Random nitpicks

Some things large and small I think could be prettier/more pythonic :wink: 

In a number of places I see constructs like this:

```python
u'%s' % \
    _(u'It is not possible to update the end period of this indicator, '
    u'because it is linked to a parent result.')
```

Is there a special reason for the string interpolation here? Also we should use format() for new string interpolating code.

##### [views/project.py#433](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/views/project.py#L433)
Shouldn't set_update be in views/project_update.py?

##### [views/project.py#442](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/views/project.py#L442)
Doesn't request.user.has_perm('rsr.post_updates', project) already return a boolean? You're using this construct in a few places and I think it's unnecessary. 

##### [models/project.py#15](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/project.py#L15)
I used to use get_model before too, but I don't think it's really worth it. It's used to optimize the code a little, but it's ugly and messes with the code lookup in the editor. Also if you're gonna use it you should remove the import of the models called with get_model, otherwise I believe the optimization is for naught.

##### [models/project.py#987](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/project.py#L987)
Why not use an ordinary boolean to indicate success?

```python
    def import_results(self):
        """Import results from the parent project."""

        if self.parents().count() == 1:
            parent_project = self.parents()[0]
        elif self.parents().count() == 0:
            return False, 'Project does not have a parent project'
        else:
            return False, 'Project has multiple parent projects'

        for result in parent_project.results.all():
            # Only import results that have not been imported before
            if not self.results.filter(parent_result=result).exists():
                self.add_result(result)

        return True, 'Results imported'
```

##### [models/indicator.py#78](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L78)
and [models/indicator.py#251](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L251): This means that children won't be updated when you change the parent, rather than create it anew. Is this right? Seems cumbersome if you have lots of children.

##### [models/indicator.py#96](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L96)
Suggested DRYification of clean():

```python
    def clean(self):
        validation_errors = {}
        fields_to_clean = ('result', 'title', 'measure', 'ascending value', )
        if self.pk and self.is_child_indicator():
            orig_indicator = Indicator.objects.get(pk=self.pk)

            for label in fields_to_clean:
                field = label.split()[0]
                if getattr(self, field) != getattr(orig_indicator, field):
                    validation_errors[field] = _(
                            u'It is not possible to update the {} of this indicator, '
                            u'because it is linked to a parent result.'.format(label))

        if validation_errors:
            raise ValidationError(validation_errors)
```

[models/indicator.py#287](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L287) and [models/result.py#66](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/result.py#L66) can also be DRYed up similarly. Come to think of it, I think you could create a _clean_children() function called in all three places. Let's discuss.

##### [models/indicator.py#336](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L336)
Can be expressed as:
```python
    bool(self.indicator.result.parent_result)
```
if you need explicit True/False. But as I'm sure you know python has the concept of "truthiness", where a number of "null" values are considered as false such as 0, empty stings, lists dicts etc so I'm not sure even the casting is needed.

##### [models/indicator.py#323](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L323)
Shouldn't this be a get() operation instead? Isn't it an error if you get more than one object back? 


##### [models/indicator.py#393](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L393)
Can be expressed as:

```python
    return max(self.percent_accomplishment, 100)
```

##### [models/indicator.py#404](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L404)
and [models/indicator.py#415](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L415): Those castings to Decimal are not needed since Indicator.baseline always returns a Decimal.

##### [models/indicator.py#418](https://github.com/akvo/akvo-rsr/blob/3a492b0454ce792994adc4e2316db2d594d9016c/akvo/rsr/models/indicator.py#L418)

Needs better documentation. If I get it right the baseline returned is either the indicator baseline_value **or** the actual value of the "previous" IndicatorPeriod.	

### Project editor

I'm adding some thoughts on the project editor too.

Dates in the project editor are not in ISO8601 format.

A nice-to-have in the project editor is to show the date selector popup with the same year-month as the Period start when you click Period end. A possible extension of this would be to set the period start of a following Indicator period to the same year-month as the previous period's end.

It's annoying to have to write 01/07/2015 when 1/7/2015 would do.

The progress bars for the project editor sections are inconsistent in behaviour. Some update the progress as you fill in fields, others only when you save. Confusing.

I'm not sure about this, it may have to do with my testing things and thus having multiple projects open in the project editor, but when you come back to a project editor tab it would be nice to be able to see in the header what project it is. E.g. instead of just the title Project Editor it could read Project editor for Water project in Ghana or Project editor for new project if it hasn't been saved yet.
