### ISSUE TITLE
Akvo IATI

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#1792]
After an initial discussion with Thomas I'm creating this issue as the basis for a discussion about an enhancement to RSR. This is a very quick sketch so there's probably lots of missing stuff and maybe even some errors :wink: 

# Akvo IATI

### What is Akvo IATI?

Akvo IATI is a limited version of RSR allowing anyone to enter project information with the main goal of being able to publish it as IATI project data.

### Capabilities

An Akvo IATI user can do the following:

* Create an Akvo IATI account, giving limited access to the MyRSR pages
* Enter project information, using a modified version of the MyRSR admin
* Publish projects entered in the IATI Project format
* See the projects in rsr.akvo.org, using a set of templates with some limitations compared to the normal RSR project templates

### Missing functionality compared to RSR

* Project information will be limited to IATI-fields, and some of the RSR-specific text fields. Notable missing parts will be images and project updates.
* The projects will only be visible on RSR, a FreeRSR user cannot create an RSR Site.

### What needs to be done?

* The user registration process needs to be wholly automated, so a user can register for an Akvo IATI account and immediately start entering project data.
* The MyRSR project editor needs a separate view for Akvo IATI users, limiting the access to IATI related fields and expanding it with simplified organisation entry.
* Access to MyRSR needs to be limited to project entry and IATI publishing. At a later stage user management might be possible if we provide for multiple Akvo IATI accounts to be linked through one organisation.
* The project templates need tweaking so that Akvo IATI projects are displayed properly even if some of what regular projects consider mandatory data is missing.

### Organisations

Probably the thorniest issue is how organisations related to Akvo IATI projects are to be managed. For one the user should (probably) be assumed to belong to the reporting organisation for the projects. So that organisation needs to be possible to add. The same goes for the participating organisations.

It seems the normal RSR data structure for organisations, using the intermediary Partnership model to link organisations to projects, won't work here. Rather the organisations related to Akvo IATI projects could be added directly in the MyRSR from and would end up in the database as objects directly related to the current project. This makes sense from an IATI standard point of view where the reporting- and participating-org fields are very limited in terms of detail. However this might result in (a lot of) duplication, but makes it much simpler to start with.

A possible enhancement could be that the system searches for possible candidates already present in the system when the user enters organisation data. E.g. if the @ref attribute is entered we can search the existing organisations and suggest matches for use.

**Comment by mtwestra** [comment]
@zzgvh, perhaps the person who registers can enter the organisation details, and these are then automatically entered in each entered project?

On the name: I am not sure it is wise to refer to RSR - what we are offering is an IATI editor, and not a free version of RSR (because you can't do typical RSR stuff such as images and updates). It comes down to marketing, but I think it is important to highlight IATI directly in the name here, as that is what we will be selling it on.

**Comment by KasperBrandt** [comment]
My initial thoughts;

### User registrations
I agree that user registrations should be fully automatic (we do need a captcha or something similar to prevent spam accounts). Currently this is almost the case, however we (purposely) built in an approval system so that every user has to be approved before he/she is linked to an organisation. I think we should keep that in place, but that's a point we can discuss. In addition, we have an outstanding issue in this milestone (#1611) which will enhance the user registration process. In particular, users should be able to select their organisation upon registering. However, what do we do with users trying to register to an organisation which is not in RSR yet?

### Organisations
On the point raised earlier, in the current project editor the user's organisation is already added as a reporting organisation. This is done so that the user can look up his project in 'My projects' (which only displays projects of the user's organisation). I think we can just copy this functionality to FreeRSR. However, I do wonder how we'll cope with adding organisations. Are the FreeRSR users allowed to add as many organisations as they want?

### Project editor
I think we'll need some changes to the editor. Albeit not a complete overhaul, we should align to IATI a bit more:
- Change the mandatory fields and the progress bar. These should be taking into account the mandatory fields of IATI v2.01, not RSR.
- Change the labels of some fields with the exact IATI names (e.g. change project to activity), and hide some fields that are irrelevant (image, etc).
- We should think about what fields to actually include in the free IATI tier. For instance, IATI only has 1 description field with 4 types (general, objectives, target groups, and other). In RSR, objectives and target groups can be mapped one to one, but general and other not. Do we keep the current RSR description fields, or do we switch to exact IATI style?

### Partnerships
I don't understand why partnerships wouldn't work for IATI? The only thing is the 'funding amount' for funding partners, which does not exist in IATI. But other than that, we can just use the current model, right?

### Discussion points
- Should we still 'approve' users when they link to an organisation for FreeRSR? If not, should we still keep this in place for normal RSR?
- How do we deal with users trying to register to an organisation that does not exist yet?
- Do we extend to the IATI organisation model as well?
- Can a user add as many organisations as they want?
- How to deal with RSR and IATI fields?
- Partnerships.

**Comment by lauraroverts** [comment]
Closing this issues, since there won't be an Akvo IATI soon.
