### ISSUE TITLE
Move to IATI currencies

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1801]
Currently, there's only 2 options for a currency in RSR: Euros and US Dollars. However, with the introduction of IATI fields we have also incorporated the IATI codelists for some fields that allow the list of IATI currencies including all possible currencies. We should extend the currencies of RSR, keeping in mind:

- [x] Project editor should allow to select all possible currencies and display it for any 'currency' field.
- [x] Show the currency code (e.g. EUR, USD, YEN) everywhere:
  - [x] Projects list
  - [x] Project page (summary, full report and finance tabs)
  - [x] Organisation page
- [x] All fields in the project editor should respond to the currency selection. When you switch to a different currency, this should happen for all fields that use a currency in the editor.

**Comment by lauraroverts** [comment]
This is becoming more important with IATI. E.g. SNV receives funding from DFID and thus will have to report this project information in pounds. 
See here the codelist of currencies used in IATI: http://iatistandard.org/201/codelists/Currency/

**Comment by damienallen** [comment]
Not really sure how individual currencies for budget items will work out considering they are summed on both the project page (finances tab) and project editor. Performing currency conversions seem like a bad idea as does removing the totals from the project page.

Thoughts?

**Comment by damienallen** [comment]
### Test plan

**Selection:** ensure all IATI currencies are selectable in project editor
- [ ] At project level
- [ ] For budget items
- [ ] For transactions
- [ ] For disbursements
- [ ] _Currency label for amounts fields in partials should update onUpdate_

**Display:** ensure 3-letter currency codes are displayed correctly

_Project page_
- [ ] Summary tab
 - [ ] Total budgets should be listed for each currency if project has budget items in multiple currencies
 - [ ] Funds needed should show a tooltip in this case, and only show funds in project currency
- [ ] Full report tab
 - [ ] Ensure currency labeling is correct (especially for items in project currency, since it is blank in budget/transaction/disbursement models)
- [ ] Finances tab
 - [ ] Budget items should be listed with assigned currency
 - [ ] Total budgets should be listed for each currency if project has budget items in multiple currencies
 - [ ] Funds needed should show a tooltip in this case, and only show funds in project currency
 - [ ] Project transactions should be listed with assigned currency

_Projects list_
- [ ] Total budgets should be listed for each currency if project has budget items in multiple currencies
- [ ] Funds needed should show a tooltip in this case, and only show funds in project currency

_Organisation page_
- [ ] Tooltip should be visible for organisations with project currencies differing from organisation currency
- [ ] Funding amounts should only include items in organisation's currency

**Comment by KasperBrandt** [comment]
- [ ] Project currency not shown for funding partners on reports tab of project page
