### ISSUE TITLE
Logs flooded with "File not found" messages

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1864]
There are a lot of "File not found" messages in our logs. Essentially not really a problem, but it makes it hard to look for any 'real' error messages when debugging.

**Comment by osgl** [comment]
They mostly seem to be the cropped or automatically processed image files -- if we could investigate whether the files are genuinely missing or just removed after the cropping process has completed and still being referenced incorrectly elsewhere in RSR -- some error handling or user feedback would be useful rather than just letting the file system responses clog up the error log files.

**Comment by punchagan** [comment]
Doesn't seem to be an issue any more.
