### ISSUE TITLE
Character limits

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1948]
## Test plan
GIVEN a project
WHEN filling in the fields in the project editor
THEN the title and subtitle should allow 200 characters
AND the project plan summary 2000 characters
AND all other descriptions no character limit

GIVEN a project page
WHEN viewing a summary longer than 400 characters
THEN a 'Read more' link should be shown
AND when clicked, the full text should show
AND when the 'Fold in' link is clicked, the truncated text should show

## Issue description
Character limits to some of the RSR fields cause trouble for partners when loading their xml files, because there are no character limits in the IATI data. 

- project title (45)
- project sub title (75)
- project plan summary (400)
- organisation name (25)
- organisation long name (75)
- Goals overview (600)
- Baseline situation (600)
- Target group (600)
- Background (1000)

This is an example http://rsr.test.akvo.org/en/project/4223/ where the project title and organisation long name ar cut off. This is a project loaded from xml by Kasper into the RSR test environment. 
![screen shot 2015-12-15 at 16 07 05](https://cloud.githubusercontent.com/assets/4179989/11814218/ede549ae-a345-11e5-97bd-fde0eb927a62.png)
![screen shot 2015-12-15 at 16 07 11](https://cloud.githubusercontent.com/assets/4179989/11814219/eff714de-a345-11e5-9341-ad1eaeb78a6d.png)

Proposal:
- When data is imported (IATI xml) there is no limit on the fields mentioned above, so no limits on a database level. 
- When data is added using the project editor, we maintain the current limits, except for project title (increase to 60) and organisation name (increase to 40)
- When showing the data on a project page, the interface allows for display in the space available. E.g. you can access the full data by clicking 'see more'.

**Comment by KasperBrandt** [comment]
My 2 cents:
- It is possible to allow any character limit in the IATI import, but I'm a bit reluctant to do so. What about you @zzgvh? It'll lead to a strange situation in which you've imported an IATI file, but can't edit the project afterwards in the project editor without shortening the title. We'd probably have to edit the IATI import to skip checks on text fields.
- Personally I'd be more in favour of increasing the character limits even more and maybe remove all character limits of the description fields (except for the project summary). I think these lengths are used by ICCO though, so that's a start. But I don't think we should be led by the example of 1 organisation too much. If another organisation comes along with titles of 65 characters, we'll be in the same situation.
- Yup, we'll have to see where we hit UI issues. So far, I can only think of the project summary that will be an issue though.

**Comment by lauraroverts** [comment]
@loicsans is going to look at the design for this

**Comment by KasperBrandt** [comment]
@lauraroverts @loicsans Are these numbers correct (I don't know how long the organisation name should become)?

- Title; 45 --> 60 characters
- Subtitle; stays at 75 characters
- Project plan summary; stays at 400 characters
- Goals overview; 600 --> unlimited characters
- Baseline situation; 600 --> unlimited characters
- Project plan; stays at unlimited characters
- Sustainability; stays at unlimited characters
- Background; 1000 --> unlimited characters
- Target group; 600 --> unlimited characters
- Organisation name; 25 --> ?? characters
- Organisation long name; stays at 75 characters

**Comment by KasperBrandt** [comment]
Just had a discussion on this with @JosjeS, and we agree on what @lauraroverts proposed in the initial issue: remove character limits during an IATI import, but stick to the character limits in the project editor. This leads to the situation that you import an IATI file, but then can't edit your project in the project editor anymore unless you shorten your fields, which might seem strange. However, this scenario almost never happens.

Organisations that import their IATI file usually have their own system of making changes (e.g. Cordaid, ICCO and RAIN all have that) and they don't make changes in RSR. In other words, their own PMS is leading and not RSR. If they want to make RSR leading, they'll indeed have to adhere to RSR's character limits. What we'll need to do:

- Skip character limit checks in the IATI import
- Add a notification in the project editor that a project has been imported and that any changes will be overwritten by the next import (we could also only show this for projects in a scheduled IATI import)
- Or possibly even disallow to make changes to a project that has been imported, since that will lead to different data in RSR compared to the 'leading system': the organisation's PMS system

What do you think @lauraroverts, @zzgvh, @mato74?

**Comment by lauraroverts** [comment]
"remove character limits during an IATI import, but stick to the character limits in the project editor" sounds logic to me

**Comment by zzgvh** [comment]
But doesn't that make RSR have two standards? How do we justify that?

**Comment by lauraroverts** [comment]
Organisations that import their projects, use their own PMS instead of the Project Editor. 

Propose to remove character limits during IATI import and add a 'read more' when the character limit we maintain in RSR is reached. And what if we remove character limits in RSR too for everything except for project title, organisation name and summary?

**Comment by KasperBrandt** [comment]
Just discussed with @lauraroverts. We will remove most of the character limits on the description fields, except for:

- Title (200 characters)
- Subtitle (200 characters)
- Project plan summary (2000 characters)
- Organisation name (40 characters)
- Organisation long name (100 characters)

**Comment by KasperBrandt** [comment]
This is how it looks now..

__Very long title and subtitle:__
<img width="1212" alt="screen shot 2016-01-19 at 13 53 10" src="https://cloud.githubusercontent.com/assets/1497367/12420910/a798de4e-bebf-11e5-939c-b0f3d6383b8f.png">

__Very long title and subtitle with keyword logos:__
<img width="1194" alt="screen shot 2016-01-19 at 14 53 39" src="https://cloud.githubusercontent.com/assets/1497367/12420922/b3998b6c-bebf-11e5-8630-9b3b194fb312.png">

__Read more button for summary:__
<img width="401" alt="screen shot 2016-01-19 at 14 53 45" src="https://cloud.githubusercontent.com/assets/1497367/12420934/befa4532-bebf-11e5-9c59-354179af6a52.png">
