### ISSUE TITLE
Move current results framework to My RSR

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1965]
Edit @kasperbrandt, to do list:

- [x] Create new top navigation for MyRSR (--> @loicsans) 
- [x] Refactor indicator update models, see #1897 (--> @kasperbrandt)
- [x] Create a full React implementation of results framework in MyRSR (--> @kasperbrandt)

------

The results framework in it’s current format (screenshot) will move to the back-end. 

![screen shot 2016-01-07 at 14 09 01](https://cloud.githubusercontent.com/assets/4179989/12171217/3a97c20e-b548-11e5-993d-9c199a5156df.png)

In MyRSR a new section My results needs to be created where results data can be entered and edited. Here, authorised users can provide and edit results data. 

Furthermore ongoing design improvements according to feedback and users stories in 2. Data entry in My Results. https://docs.google.com/document/d/1AbiHHkbmQLEMLXIJAe0j5fqJlfVKzvLt65JdzbGRvyM/edit

**Comment by KasperBrandt** [comment]
Some notes:
- It would be nice to have a full React implementation, instead of the current half Django / half React implementation of the results framework.
- If we create an 'editable' variable, we can actually use the same React component for the front-end, but then without editing functionality. This'll save a lot of work on the front-end implementation, but it won't allow for a lot of customisation of the front-end compared to the back-end.

**Comment by KasperBrandt** [comment]
I'll close this issue, but the results framework is still in an iterative process, so we'll keep improving it.
