### ISSUE TITLE
Project editor improvements

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1999]
- [x] We offer http://mygeoposition.com to look up the coordinates. But to partners it's not clear what they need to fill in in Latitude Longitude. Some people click on Copy (x,y) and paste that in one of the field, but that doesn't work, since you need to copy past the Lat / Long separately. 
![screen shot 2016-02-12 at 10 59 13](https://cloud.githubusercontent.com/assets/4179989/13003805/e3687b8a-d177-11e5-8036-6826a2196fb5.png)

- [x] It's not possible to select a year when you fill in the start/end date. If your project started in 2000, it means you need to go back month by month. 
![screen shot 2016-02-12 at 11 02 49](https://cloud.githubusercontent.com/assets/4179989/13003884/4a9782ba-d178-11e5-9b47-f598725fdfba.png)

- [x] Fix the helptext of a sector code. It now states the codelists will be loaded when DAC-3 or DAC-5 vocabulary is chosen, while this is not true anymore.

- [x] ‘Sector code not found’ - propose to replace this with the data that has been entered.

- [x] Add explanations what the keywords are meant for in section 10 - Project comments and keywords. This is not clear to partners.

- [x] Change explanation of "Links and documents" to include the 5MB file size limit. You don't see that when there's already documents uploaded.

- [x] Remove feedback button (we have HELP button already)

**Comment by KasperBrandt** [comment]
## Test plan
In the project editor:
- [ ] The help texts for locations (latitude / longitude) should point to http://www.latlong.net/, and not to http://mygeoposition.com.
- [ ] Any date picker should have a year dropdown, and a 'Today' button. This component has changed slightly, so check that saving and deleting a date still works.
- [ ] The help text for sector > sector code should not mention that only DAC-3 and DAC-5 sectors can be picked. It should, however, still state where the DAC-3 and DAC-5 sector codes can be found.
- [ ] The unicode description of sectors is updated, it should now always be in this form: "**sector_vocabulary name**: **sector_code** - **sector_description** (**sector_percentage**%). In case of correct DAC-3 or DAC-5 codes, the description should be filled automatically.
- [ ] Keyword labels should now have a help text, and in addition the help text of section 10 should mention the same: "Select keywords in case you are using an Akvo Page. Keywords linked to a project will determine if a project appears on the Akvo Page or not."
- [ ] The general help text of section 9 should include the mention of a 5 MB limit for uploading documents.
- [ ] The 'Provide feedback' button on the right side should not appear anymore, since we now have the general 'HELP' button there.
