### ISSUE TITLE
Show error message if image file is too big when placing update (estimate: 6)

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2040]
Currently, placing an update fails silently when the image attached is too big. We should add a nice error message for that.

**Comment by punchagan** [comment]
@nadiagorchakova Can you remind me if this issue is for the RSR website or for Up app? 

If this is for the web-site, this [discussion seems relevant](https://github.com/akvo/akvo-rsr/issues/324).  But, the limit for the web-site has been made [way higher](https://github.com/akvo/akvo-provisioning/issues/277), so this is no longer an issue. 

We could add a front-end check, but I think this is not all that important anymore. Thoughts? /cc @zzgvh

**Comment by nadiagorchakova** [comment]
@punchagan The issue is for RSR website.

Right now RSR can handle images less than 3.5mb in size. However, as far as I know, partners with poor internet connection in project countries still face the issue. It takes too much time to load and the update page probably times out. 
I also see that in here https://github.com/akvo/akvo-rsr/issues/219 Kasper wrote some code to add help text on max image size. I don't see it implemented in RSR though. Would be helpful to have it implemented, in addition to the post-factum error message.
