### ISSUE TITLE
Sector codes in project editor

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2223]
- [x] Remove permanent help text for sectors.
- [x] Select DAC-3 and DAC-5 from lists.
- [x] Remove sector mandatory for RSR validation set. Also in publishing status checks.

**Comment by damienallen** [comment]
### Test plan

- [ ] Sector should no longer be a required field in RSR (must run migration first)
- [ ] Permanent help text should no longer be present
- [ ] In 'Project Focus - Sectors', sector codes for DAC-3 and DAC-5 vocabularies should be selectable by dropdown and otherwise by text input.
- [ ] Section should still function when sector vocabularies/codes are changed with/without saving, and also if new sectors are added.
