### ISSUE TITLE
Update actual values of parent through project editor

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2307]
Currently, the actual values only of a parent project only get updated when an indicator update is placed in the 'My results' section. However, adding or changing the value in the project editor should give the same result.

**Comment by damienallen** [comment]
### Test plan

- [ ] Updates made in project editor should aggregate (both units and percentage)
- [ ] `update_actual_value` should never enter an infinite loop (due to `update_parents` argument)
- [ ] Ensure existing aggregation functionality still works
 - [ ] Aggregation toggles
 - [ ] Switching between numerical and non-numerical values
 - [ ] Deleting updates
