### ISSUE TITLE
Better backup strategy for the DB

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2427]
We need to review our backup, retention and restore/recovery policies and come up with a better strategy.  Below are some notes to get a discussion going. 

## Backups
- We currently just have compressed pg_dumps of the DB, taken nightly. 
- Removing unused Django models drops their tables. We need to have backups before every such migration is done, essentially, a backup before every release ("releas-backups"). (The web-app needs to be thoughtful, too, and not just rely on the backups - @kardan)
- Postgres 9.1 and later have support for Point in-time recovery (PITR) using pg_basebackup + transaction log backup.  Should we have that, along with the dumps that we already do? 
## Retention
- Our official DB backups seem to retain just one week's (nightly) backups and no more. Is this too little? 
- It would be useful to retain a large number of  "release-backups". May be upto an year?
## Restore
- @LarsSjogreen suggested having regular (half year?) fire drills when we practice restoring the system from backup, both to verify that the backup works but also to make sure all team members know what to do if we need to do disaster recovery.

**Comment by zzgvh** [comment]
My 2 ¢: I think nightly backups are adequate, with "release-backups" being a good addition. Retention should be improved, something like keeping all backups for a week, one backup per week for a month and one backup per month for a year+. And maybe all release-backups for a year+, they won't be all that many.

Not sure PITR is of any use to us since that presumes we know exactly when a backup related problem occurred (I'd guess) which might be hard. I'm sure there are scenarios where it would be useful, but I'd say it comes down to how complicated it is to setup compared to what extra data security it provides.

Backup drills sounds like a good idea!

Do we want off-site backups (intermittently made) to secure against total failure of CloudVPS? (Maybe we already do it this way?)

**Comment by LarsSjogreen** [comment]
I like your €.02 backup plan Gabriel!

 

An offsite backup (trusted location) sounds like a good idea as long as we can find one that conforms with organization policy on data security. (Cost wise, backup storage tends to be quite cheap as long as Cloud VPS don’t charge us extra for outgoing traffic.) This needs some thought though, especially if we set up national instances of RSR because of data storage regulations from the partner. Then we need to also provision local off site backup.

 

Also, it sounds like there’s buy in on the whole fire drill thing. Any suggestions how we do this? What level of realism do you want? (#evilgrin #chaosmonkey)

We should set up a scenario/plan and then time box for a drill like this. If you also want surprise (and grades on response time from “down” to “running”) then Nadia can probably mark off some time in secret in the RSR planning after we’ve decided how the drill should be acted out. Surprises are nice, right?

 

/Lars

 

Från: Gabriel von Heijne [mailto:notifications@github.com] 
Skickat: den 9 november 2016 11:31
Till: akvo/akvo-rsr <akvo-rsr@noreply.github.com>
Kopia: Lars Sjögreen <lars.sjogreen@akvo.org>; Mention <mention@noreply.github.com>
Ämne: Re: [akvo/akvo-rsr] Better backup strategy for the DB (#2427)

 

My 2 ¢: I think nightly backups are adequate, with "release-backups" being a good addition. Retention should be improved, something like keeping all backups for a week, one backup per week for a month and one backup per month for a year+. And maybe all release-backups for a year+, they won't be all that many.

Not sure PITR is of any use to us since that presumes we know exactly when a backup related problem occurred (I'd guess) which might be hard. I'm sure there are scenarios where it would be useful, but I'd say it comes down to how complicated it is to setup compared to what extra data security it provides.

Backup drills sounds like a good idea!

Do we want off-site backups (intermittently made) to secure against total failure of CloudVPS? (Maybe we already do it this way?)

**Comment by orifito** [comment]
Good news is that we already have off-site backups into Hetzner. 
I also agree on having "release-backups", and I'm not against revisiting current retention policies.

**Comment by nadiagorchakova** [comment]
Thanks @orifito for reviewing it. We have the next RSR release planned for December 1st. Could we kick off the release backup idea next week then?
I also like what Gabriel suggested regarding retention policy: "keeping all backups for a week, one backup per week for a month and one backup per month for a year+. And maybe all release-backups for a year". Is it something that the dev ops team needs to discuss internally first before we implement it?

**Comment by orifito** [comment]
Yes I do think we can kick off the release backup next week. 
With regard to retention policy, the proposed approach looks fine and we can implement it asap.

**Comment by punchagan** [comment]
@orifito Let me know if you need any help with this.  If you want me to start looking into this, I can start off if you tell me where this code resides.

**Comment by orifito** [comment]
@punchagan new backup strategy and retention policies have been already configured, so this can be included in next release.

**Comment by punchagan** [comment]
Thanks, @orifito
