### ISSUE TITLE
MFA 2016 report Plan Finland

### ISSUE THREAD

**Issue by akvotender** [akvo/akvo-rsr#2648]
Creation of annual report 2016.

**Comment by Geerts** [comment]
To do:
1.  Combine actual comment boxes with 2015 and 2016. Plan Finland will report for 2 periods, but the actual comment boxes take quite some space because we have to duplicate the labels for the results.  Can we combine the actual value comments in one box with the year of the period so:
[year of indicator period start:] [actual value comment]
[year of indicator period start:] [actual value comment]

2.  Results shouldn’t start on a new page. I didn't see a page break:before on the results group nor on the results title so not sure where it comes from. 

3.  Is it possible to remove the empty comment boxes from the report if there is no text in the box?

**Comment by Geerts** [comment]
@stellanl  Hi Stellan, did you manage to have a look at this last Friday?

**Comment by stellanl** [comment]
I got started, but we had a bad db bug in flow so not done yet. Will
continue later today

**Comment by stellanl** [comment]
1. Interesting challenge. Have to do more experiments
2. There was a "break-after: always" on the "Read more in RSR" label. I set it to "auto" instead.
3. Yes, the table row can be made conditionally in visible.

**Comment by akvotender** [comment]
1. Alright, please let me know when we can finish this.
2. Perfect
3. Please implement :)

**Comment by stellanl** [comment]
I found how to do 1. Do you also want to consolidate the results themselves, so that both periods immediately follow each other under the same TARGET, BASELINE and ACTUAL headings?

**Comment by stellanl** [comment]
All three items implemented, except for the raising of the column headers.

**Comment by Geerts** [comment]
Completed, can be found on live rs.
