### ISSUE TITLE
Disaggregated indicators for new Results Framework 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2674]
The validated design: 

https://projects.invisionapp.com/share/V8B3AI1FH#/screens/226453925

**Comment by zzgvh** [comment]
One thing that comes to mind is that I think we need a unified design that takes into consideration that we can have more than one update for an indicator period, even if we don't allow that for dis-aggregated updates. Otherwise implementing the UI will be harder/more work and there will not be consistency from the user's point of view.

**Comment by punchagan** [comment]
Closed in #2839
