### ISSUE TITLE
Active filter should be kept when changing number of projects viewed

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2684]
When changing the number of projects shown in the project directory, any filter that is in force should be "brought along".

**Comment by punchagan** [comment]
@zzgvh This seems to be the case already. I couldn't reproduce the bug described here. Could you describe how to reproduce it? Thanks!

**Comment by punchagan** [comment]
@zzgvh Have been able to reproduce this now, based on our conversation. Thanks!

**Comment by punchagan** [comment]
When the page size has been set, and if any filters are applied after that, the page size is reset to the default value of 10. This is because the page size is set using a query parameter `limit` and the form submission occurring when a filter is applied doesn't retain this query parameter. Only the parameters in the form are retained in the URL.

**Comment by zzgvh** [comment]
Heh, this not only works, but also keeps the advanced filter tab open after applying the filter. Without cookies! 😉
