### ISSUE TITLE
'Pushing' page layout right when 'Advanced Filter' window is open 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2716]
The upgraded Advanced Filter window overlaps with the search results, obscuring the complete view of the search listing: 

![advanced filter 1](https://cloud.githubusercontent.com/assets/26227538/26780032/209d9758-49e8-11e7-81ad-ab7194a40c3a.jpg)

Would be better to push the view of the search results to the right of the page so that it looks similar to this: 

![advanced filter 2](https://cloud.githubusercontent.com/assets/26227538/26780250/28f4f792-49e9-11e7-885a-9f5c8bf195a9.jpg)

**Comment by Kiarii** [comment]
not sure what we would push to the right or how, but since the filter is on the right, maybe its fields shd open underneath. collapsing the rest of the project detail's content will require some curtailing back on its lot to declutter the interface. perhaps we can start a conversation on that note?
 
![image](https://user-images.githubusercontent.com/12692444/26933447-4216d028-4c6f-11e7-8bf6-d345ee6f4403.png)

**Comment by punchagan** [comment]
No longer a concern with the changes in #3046
