### ISSUE TITLE
Design for updates outside the accordion

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2724]
The design for the Results page does not fully take into account that there may be more than one indicator period update (called just **update** from hereon) for a given indicator period. This needs a little design love.

Currently the design looks [like this](https://projects.invisionapp.com/share/M6AQCRWU8#/screens/222113069):
![screenshot_181](https://user-images.githubusercontent.com/142613/27134310-7c90fc24-5115-11e7-93f3-1da23809ebc6.png)

[and when you click](https://projects.invisionapp.com/share/M6AQCRWU8#/screens/222113070) on the period the update is shown in the right hand pane:

![screenshot_182](https://user-images.githubusercontent.com/142613/27134369-a2bdc5da-5115-11e7-855c-f51af7b8b4ac.png)

The current implementation allows for more than one update in a single indicator period:

![screenshot_183](https://user-images.githubusercontent.com/142613/27134496-0d3c7ffa-5116-11e7-8b0f-cf7ce2497e98.png)

![screenshot_184](https://user-images.githubusercontent.com/142613/27134933-896ee472-5117-11e7-84d4-0f9aa442e83a.png)

necessitating some more design around how to show and manipulate them when the updates are not inline in the accordion.

**Comment by Kiarii** [comment]
A number of thoughts arise when I think about this issue:
- what would be the status of the period if it has multiple updates in different states
- multiple updates also throws into a disarray, the bulk actions; if an M&E sends out update requests for periods without updates, then those with 'intermediate (submitted, approved) updates' are hard to dig out to include in such requests
- there was also a history feature in the cards: where a log is kept of changes made to in the update even if this is not submitted; i.e. a period has a single update, but intermediate Saves can be viewed in the log  
- approving an update may be the step via which a period is auto-locked from receiving further updates. Multiple updates disable this possibility and increase the workload since each (multiple update) period has to be locked manually 
- it appears breaking down the period into multiple periods would alleviate various issues that may arise from an update 'overloaded' period e.g. creating 3 1-month periods out of a single 3-month period

**Comment by punchagan** [comment]
This has been resolved, elsewhere.
