### ISSUE TITLE
Latency when clicking 'Save' and/or 'Submit for Approval' for Indicator Updates in the new results framework 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2739]
3-4 second delay experienced in testing by Anthony, and also by Ethel during training for One Drop.

**Comment by punchagan** [comment]
Short term: Add a spinner to give UI feedback to the user

**Comment by punchagan** [comment]
Short term fix applied in #2752

**Comment by zzgvh** [comment]
I think part of the performance problem might be the Alert component we're using. Looking at the Redux log output I see a lot of those components being destroyed and created anew whenever the accordion is re-rendered. This needs to be investigated as the problem seems to grow more than linearly with the number of indicators for a project.

**Comment by AkvoAnt** [comment]
https://media.giphy.com/media/xT1Ra6GfykNLfR2YPm/giphy.gif

**Comment by punchagan** [comment]
Not sure if all the latency problems have been fixed, but this ticket can be re-opened with specific cases to reproduce, if we find there are still problems.
