### ISSUE TITLE
Allow adding internal notes during any time in an update's lifecycle

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2862]
Internal notes can be only added by a project editor after an update has been saved, and before it is submitted for review/approval.  A project editor should be allowed to add notes to an update in any state.

**Comment by zzgvh** [comment]
Also it should be possible to add a note as the first action taken when opening the update form with a new update. This would imply that the update is created with empty values and a note is attached to it.

One question that follows is what happens if the user closes the update after having added a note only and not explicitly pressed Save. Do we delete the update and the note?
