### ISSUE TITLE
New UI refinement

### ISSUE THREAD

**Issue by loicsans** [akvo/akvo-rsr#3127]

**Comment by zzgvh** [comment]
### Random notes on the UI

##### RSR logo URL

![screenshot_250](https://user-images.githubusercontent.com/142613/36538310-31602cb8-17d3-11e8-91f0-983bfb401946.png)

The AkvoRSR logo's URL is inconsistent. If you're logged in you end up on the My projects list, if you're not you get the regular landing page. Shouldn't the logo be a "home" button, with consistent behaviour?

Also the current behaviour leads to it being impossible to get to the project listing page from the updates and orgs listing pages if you're logged in.

##### User management

![screenshot_251](https://user-images.githubusercontent.com/142613/36538910-5ccf8856-17d5-11e8-8db8-f4e2848fac0b.png)

I still don't agree with the placement of this link. I feel its place should be under the select with the user name.

##### User first and last name can be " "(space)

Leading to this 😛: 

![screenshot_252](https://user-images.githubusercontent.com/142613/36539669-d7c3efc8-17d7-11e8-8961-f2fe52f02f40.png)

##### Objects shown should be a multiple of 3

![screenshot_253](https://user-images.githubusercontent.com/142613/36539840-72576290-17d8-11e8-9ed2-b91f3bfc6a08.png)

Since we show three projects per row in the project list, the number of projects fetched to a page should be a multiple of three. And the links to see more projects in one go should also be changed. How about 24, 48 and 96?

The same changes apply to updates and organisations of course.

##### Undefined projects

The text below the location filter showing the number of projects currently in the filter always ends with "undefined": 

![screenshot_254](https://user-images.githubusercontent.com/142613/36540363-50837c7e-17da-11e8-9847-e7cea40c67c6.png)

##### Filter issues

The filters are missing two buttons. Apply and Clear. Right now you can apply the filter by pressing search, but that's very counterintuitive and there's no way to get rid of the filter!

##### Filters work differently for updates and organisations

The "old way" of filtering is still in place for updates and organisations. I like the new display of the filters and it should be used for all three pages. Maybe it's a work in progress?
