### ISSUE TITLE
More granular project level permissions per user

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#3217]
The idea is to give users more granular permissions, and be able to specify which projects they have permissions to access, among the projects they would already get access to by virtue of their employments.

**Comment by zzgvh** [comment]
# This is hard

The current solution with a "white list" for a user is not enough given that we have employments. They make things a lot harder. Below I've outlined how a user is associated with projects via employments and the complexities in the determining of user association with projects.

## RSR user permissions

The RSR permissions system is based around a few simple concepts. However over the years these initially simple rules have been modified and extended and are now quite complicated.

The **core rules** are that a user is associated with an org and the org is in turn associated with a number of projects. The user has access to all projects that its org has access to.

A user can have one or more roles (also called groups), e.g. **Admins** or **User Managers**. A role limits what a user is allowed to do when interacting with RSR, both the projects and in other areas. Note however that _which_ projects a user can access is not determined by the role, this is governed by the rules of association as per above.

However these rules of association are complicated by a number of other rules added to the **core rules**.

### Employments

One of the concepts added is that of employments. An employment is the combination of a user's association with one organisation and a role that determines the user's access rights in RSR. This corresponds to the **core rules** above. 
However, a user can have more than one employment. Since these can be for different orgs the projects that a user has access to can be the combination of several sets of projects associated with different orgs. And the roles of the employments may be different meaning that the user may have different limitations for the sets of projects.

### Content owner

An org can be the **content owner** of another org. This other or is **content owned**. A content owner org gets access to the projects associated with the content owned org. Content ownership can happen in two ways, one explicit and one implicit. 

#### Explicit content ownership
An org can have the content_owner field to point to another org. This other org is the content owner. Content ownership is set up in this way automatically when importing projects using the RSR IATI import. Orgs created during the import are set to be content owned by the reporting org of the project.

#### Implicit content ownership
Orgs are implicitly content owned when they are implementing partners and are not allowed to create projects.

### User management

The user management page in MyRsr is a list of employments that the currently logged in user, called the **user manager** can change. The user manager can also add new employments here.

The list of employments the user manager can access is determined as follows:

 - If the user manager is a Django superuser or admin then all users in RSR are available. 

 - Otherwise the list is populated thus:
   - Get a list of the orgs the user has the **rsr.user_management** permission for. This means being part of the **Admins** or **User admins** groups.
   - Extend this list of orgs with all orgs that are content owned by the orgs. See above for details on how content ownership is determined.
   - Find all employments associated with the list of orgs from the previous step

## Limiting users access to projects

Per the rules above a user has access to all projects associated with orgs where she is employed _and_ all orgs that are content owned by any orgs where she is employed.

A user manager may only have access to some of the projects that a user she manages has access to. This is because the user manager may not have the same employments as the user, and may have access to a different set of projects as a result.

Also a user may have access to a project in different roles via different employments.

We want to limit access to only certain projects of those that are accessible by association via employments. The above taken together creates the feeling that there are hidden edge cases here that are at least hard to deal with. I'll end with an example that is at least non-trivial to solve.

### An example of how thorny it can be to determine access

Alice is a user with three employments: She's an Admin and an M&E manager for org A and she's also an M&E manager for org B.

Bob is a user with two employments: he's Admin for org A and Admin for org B

Bob views the User management page, there he sees three employments for Alice: as Admin for A, as M&E manager for A and as M&E manager for B.

Now imagine that we want a page that lists the projects that can be limited for Alice. This page would show the projects of org B and Bob could select which of these projects Alice could access. Since Alice is an admin of org A her access to A's projects cannot be limited. 

If orgs A and B share a project then this project cannot be part of the list of projects that Alice cannot have access to. How do we _not_ include the shared project in the list of projects? Alternatively the project appears on the list, but Alice has access anyway though her Admin role in org A. But this is misleading to Bob who thought he could limit Alice's access.

**Comment by zzgvh** [comment]
This code is superseded by the #3355 code. Closing.
