### ISSUE TITLE
Extend endpoints with children

### ISSUE THREAD

**Issue by martinchristov** [akvo/akvo-rsr#3652]
- [ ] /transaction/ with **sectors**
Please add a "sectors" array to the GET /transaction/ method in order to prevent X*Y calls being made to /transaction_sector/

- [ ] /project_location/ with **administratives**
Please add an "administratives" array to the GET /project_location/ method in order to prevent X*Y calls being made to /administrative_location/

- [ ] /project_document with **categories**
Please add a "categories" array containing IDs only
example response:
`
	[
		{url: "http://...", categories: ['A01', 'A02'], ...}
	]
`
Please have GET, POST & PATCH handle the categories as an array.

**Comment by punchagan** [comment]
Since we are using different parameters for end-points, already, you could work around the X*Y requests for now, by adding some more conditionals on the params.

Administrative locations for the project can be fetched by adding a parameter like `location__location_target={id}`

Similarly, `transaction__project={id}` for transaction_sectors.
