### ISSUE TITLE
Output data from Updates

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#997]
Add ability to export the data from project updates
- [ ] Link to the XML/JSON API data call
- [ ] Download as PDF
- [ ] Make selection based on date range
- [ ] Include or Exclude Images in export

**Comment by lauraroverts** [comment]
@Geerts could you look at this? A new report for My Reports. Propose to create a report that shows one update per page, with the ability to include images and add a date filter.

**Comment by lauraroverts** [comment]
Information that is at least required for this report:

- username and organisation that posted the update
- data of update
- Date project was updated last time
- Projects without updates
- How many updates per user

Phylis is going to talk to the Dutch Embassy in Kenya about any other requirements. They are one of the partners that requested this report, because they want to keep track of who is posting updates and how often to which project.

**Comment by Geerts** [comment]
Inactive.
